// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspireApp.ApiService.Models;

public partial class CursorState
{
    public int Id { get; set; }

    public string NextCursor { get; set; }

    public DateTime LastUpdated { get; set; }
}