// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspireApp.ApiService.Models;

public partial class Tag
{
    public Guid Id { get; set; }

    public Guid MarketId { get; set; }

    public string Name { get; set; }

    public virtual Market Market { get; set; }
}