// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspireApp.ApiService.Models;

public partial class Token
{
    public Guid Id { get; set; }

    public Guid MarketId { get; set; }

    public string TokenId { get; set; }

    public string Outcome { get; set; }

    public decimal Price { get; set; }

    public bool Winner { get; set; }

    public virtual Market Market { get; set; }
}